import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { once } from 'node:events';
import WebSocket from 'ws';
import JSZip from 'jszip';
import ExcelJS from 'exceljs';
import { existsSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';

test('login, independent rooms, live events, upload/download, retry, revocation and persistence',async()=>{
  const dir=await mkdtemp(path.join(tmpdir(),'multiworks-test-'));
  const port=32000+Math.floor(Math.random()*10000),origin=`http://127.0.0.1:${port}`;
  let child,ws;
  async function start(){child=spawn(process.execPath,['server.js'],{env:{...process.env,PORT:String(port),HOST:'127.0.0.1',DATA_DIR:dir,MAX_FILE_MB:'1',PUBLIC_ORIGIN:origin},stdio:['ignore','pipe','pipe']});await Promise.race([once(child.stdout,'data'),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Server startup timed out')),10000).unref())]);}
  async function stop(){const done=once(child,'exit');child.kill();await done;}
  async function request(route,{cookie,body,method='GET',headers={}}={}){return fetch(origin+'/api'+route,{method,headers:{'Content-Type':'application/json','X-Workspace-Request':'1',Origin:origin,...(cookie?{Cookie:cookie}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});}
  try{
    await start();
    assert.equal((await request('/rooms')).status,401);
    assert.equal((await request('/login',{method:'POST',body:{password:'short'}})).status,400);
    const device1=randomUUID(),device2=randomUUID();
    const login1=await request('/login',{method:'POST',body:{password:'a-long-test-password',deviceId:device1,deviceName:'电脑'}});
    assert.equal(login1.status,200);const cookie=login1.headers.get('set-cookie').split(';')[0];
    const login2=await request('/login',{method:'POST',body:{password:'a-long-test-password',deviceId:device2,deviceName:'手机'}});const cookie2=login2.headers.get('set-cookie').split(';')[0];
    const initial=(await (await request('/rooms',{cookie})).json())[0];
    const room=await (await request('/rooms',{cookie,method:'POST',body:{name:'项目 B'}})).json();
    ws=new WebSocket(`ws://127.0.0.1:${port}/ws`,{headers:{Cookie:cookie2,Origin:origin}});await once(ws,'open');
    const event=once(ws,'message');
    const clientId=randomUUID();
    const sent=await (await request(`/rooms/${initial.id}/messages`,{cookie,method:'POST',body:{body:'测试实时同步 <script>alert(1)</script>',clientId}})).json();
    const live=JSON.parse((await event)[0].toString());assert.equal(live.message.id,sent.id);
    const retry=await (await request(`/rooms/${initial.id}/messages`,{cookie,method:'POST',body:{body:'重复请求',clientId}})).json();assert.equal(retry.id,sent.id);
    assert.equal((await (await request(`/rooms/${room.id}/messages`,{cookie:cookie2})).json()).length,0);
    assert.equal((await request(`/rooms/${initial.id}/messages`,{cookie,method:'POST',body:{body:'blocked',clientId:randomUUID()},headers:{Origin:'https://evil.example'}})).status,403);
    const form=new FormData();form.append('file',new Blob(['pdf-content']), '工作.pdf');form.append('clientId',randomUUID());
    const uploaded=await fetch(origin+`/api/rooms/${room.id}/files`,{method:'POST',headers:{Cookie:cookie,'X-Workspace-Request':'1',Origin:origin},body:form});assert.equal(uploaded.status,200);const file=await uploaded.json();assert.equal(file.file_name,'工作.pdf');
    async function uploadFixture(name,contents){
      const form=new FormData();form.append('file',new Blob([contents]),name);form.append('clientId',randomUUID());
      const response=await fetch(origin+`/api/rooms/${room.id}/files`,{method:'POST',headers:{Cookie:cookie,'X-Workspace-Request':'1',Origin:origin},body:form});
      assert.equal(response.status,200);return response.json();
    }
    assert.equal((await request(`/files/${file.id}/preview`)).status,401);
    assert.equal((await request(`/files/${file.id}/content`,{cookie})).status,415);
    const pdf=await uploadFixture('预览.pdf','%PDF-1.4\n%%EOF');
    const pdfMeta=await (await request(`/files/${pdf.id}/preview`,{cookie})).json();assert.equal(pdfMeta.kind,'pdf');
    const inline=await request(`/files/${pdf.id}/content`,{cookie});assert.equal(inline.status,200);assert.match(inline.headers.get('content-disposition'),/^inline/);assert.match(inline.headers.get('content-type'),/application\/pdf/);
    const html=await uploadFixture('不执行.html','<script>window.secret=1</script>');
    const textPreview=await (await request(`/files/${html.id}/preview`,{cookie})).json();assert.equal(textPreview.kind,'text');assert.equal(textPreview.text,'<script>window.secret=1</script>');assert.equal((await request(`/files/${html.id}/content`,{cookie})).status,415);
    const archive=await uploadFixture('归档.zip','not-an-office-file');assert.equal((await (await request(`/files/${archive.id}/preview`,{cookie})).json()).kind,'unsupported');
    const document=new JSZip();
    document.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');
    document.file('word/document.xml','<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Word 正文预览测试</w:t></w:r></w:p></w:body></w:document>');
    const docx=await uploadFixture('文档.docx',await document.generateAsync({type:'nodebuffer'}));
    const docxPreview=await (await request(`/files/${docx.id}/preview`,{cookie})).json();assert.equal(docxPreview.kind,'text');assert.match(docxPreview.text,/Word 正文预览测试/);
    const workbook=new ExcelJS.Workbook();workbook.addWorksheet('项目').addRow(['Excel 预览测试',123]);
    const xlsx=await uploadFixture('表格.xlsx',await workbook.xlsx.writeBuffer());
    const xlsxPreview=await (await request(`/files/${xlsx.id}/preview`,{cookie})).json();assert.equal(xlsxPreview.kind,'spreadsheet');assert.deepEqual(xlsxPreview.sheets[0].rows[0],['Excel 预览测试','123']);
    const allFiles=await (await request('/files',{cookie})).json();assert.equal(allFiles.length,6);assert.equal(allFiles[0].room_name,'项目 B');
    assert.equal((await (await request(`/search?q=${encodeURIComponent('实时同步')}`,{cookie})).json())[0].id,sent.id);
    for(let i=0;i<110;i++)await request(`/rooms/${initial.id}/messages`,{cookie,method:'POST',body:{body:`历史消息 ${i}`,clientId:randomUUID()}});
    const context=await (await request(`/messages/${sent.id}/context`,{cookie})).json();assert.equal(context.roomId,initial.id);assert.equal(context.messages[0].id,sent.id);assert.equal(context.hasAfter,true);assert.equal(context.hasBefore,false);
    const deletionEvent=new Promise(resolve=>ws.on('message',raw=>{const event=JSON.parse(raw);if(event.type==='room-deleted')resolve(event);}));
    const disposableRoom=await (await request('/rooms',{cookie,method:'POST',body:{name:'待删除的项目'}})).json();
    const temporaryForm=new FormData();temporaryForm.append('file',new Blob(['temporary-content']),'待删除.txt');temporaryForm.append('clientId',randomUUID());
    const temporary=await (await fetch(origin+`/api/rooms/${disposableRoom.id}/files`,{method:'POST',headers:{Cookie:cookie,'X-Workspace-Request':'1',Origin:origin},body:temporaryForm})).json();
    assert.equal(existsSync(path.join(dir,'files',temporary.file_key)),true);
    assert.equal((await request(`/rooms/${disposableRoom.id}`,{cookie,method:'DELETE'})).status,200);
    assert.equal((await deletionEvent).roomId,disposableRoom.id);
    assert.equal(existsSync(path.join(dir,'files',temporary.file_key)),false);
    assert.equal((await request(`/files/${temporary.id}`,{cookie})).status,404);
    assert.equal((await request(`/rooms/${disposableRoom.id}/messages`,{cookie})).status,404);
    assert.equal((await request(`/files/${file.id}`)).status,401);
    const download=await request(`/files/${file.id}`,{cookie:cookie2});assert.equal(await download.text(),'pdf-content');assert.match(download.headers.get('content-disposition'),/attachment/);
    const range=await request(`/files/${file.id}`,{cookie:cookie2,headers:{Range:'bytes=0-2'}});assert.equal(range.status,206);assert.equal(await range.text(),'pdf');
    const large=new FormData();large.append('file',new Blob([new Uint8Array(1048577)]),'large.zip');large.append('clientId',randomUUID());assert.equal((await fetch(origin+`/api/rooms/${room.id}/files`,{method:'POST',headers:{Cookie:cookie,'X-Workspace-Request':'1',Origin:origin},body:large})).status,413);
    await request(`/devices/${device2}/sessions`,{cookie,method:'DELETE'});assert.equal((await request('/rooms',{cookie:cookie2})).status,401);
    ws.close();await stop();
    const retentionDatabase=new DatabaseSync(path.join(dir,'workspaces.sqlite'));
    retentionDatabase.prepare('UPDATE messages SET created=? WHERE id=?').run(946684800000,sent.id);retentionDatabase.close();
    await start();
    const retained=await (await request(`/messages/${sent.id}/context`,{cookie})).json();
    assert.equal(retained.messages.find(message=>message.id===sent.id).created,946684800000);
    const firstPage=await (await request(`/rooms/${initial.id}/messages`,{cookie})).json();assert.equal(firstPage.length,100);
    const olderPage=await (await request(`/rooms/${initial.id}/messages?before=${firstPage[0].id}`,{cookie})).json();assert.equal(olderPage.length,11);assert.equal(olderPage[0].id,sent.id);
    const persisted=await (await request(`/rooms/${room.id}/messages`,{cookie})).json();assert.equal(persisted[0].file_name,'工作.pdf');
    assert.equal(await (await request(`/files/${file.id}`,{cookie})).text(),'pdf-content');
    assert.equal((await (await request(`/rooms/${room.id}/messages?q=${encodeURIComponent('工作')}`,{cookie})).json()).length,1);
    assert.equal((await (await request(`/rooms/${initial.id}/messages?q=${encodeURIComponent('工作')}`,{cookie})).json()).length,0);
    assert.equal((await request(`/messages/${file.id}`,{cookie,method:'DELETE'})).status,200);
    assert.equal((await request(`/files/${file.id}`,{cookie})).status,404);
    assert.equal((await request(`/rooms/${room.id}`,{cookie,method:'DELETE'})).status,200);
    assert.equal((await (await request('/files',{cookie})).json()).length,0);
    assert.equal((await request(`/files/${docx.id}/preview`,{cookie})).status,404);
    assert.equal((await request(`/rooms/${initial.id}`,{cookie,method:'DELETE'})).status,200);
    assert.equal((await (await request('/rooms',{cookie})).json()).length,0);
    const recovery=await request('/rooms',{cookie,method:'POST',body:{name:'重新开始'}});assert.equal(recovery.status,200);
  }finally{ws?.terminate();if(child?.exitCode===null)await stop();await rm(dir,{recursive:true,force:true});}
});
